In [8]:
##   Uniavriate Diabetic Readmission
import pandas as pd
import numpy as np
data = pd.read_csv(r"D:\smart decision\Data Preprocessing\Cleaned Datasets\cleaned_diabetic_data.csv")
data

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),6,25,1,1,41,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,59,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,11,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),1,1,7,2,44,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),1,1,7,1,51,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101761,443847548,100162476,AfricanAmerican,Male,[70-80),1,3,7,3,51,...,No,Down,No,No,No,No,No,Ch,Yes,>30
101762,443847782,74694222,AfricanAmerican,Female,[80-90),1,4,5,5,33,...,No,Steady,No,No,No,No,No,No,Yes,NO
101763,443854148,41088789,Caucasian,Male,[70-80),1,1,7,1,53,...,No,Down,No,No,No,No,No,Ch,Yes,NO
101764,443857166,31693671,Caucasian,Female,[80-90),2,3,7,10,45,...,No,Up,No,No,No,No,No,Ch,Yes,NO
101765,443867222,175429310,Caucasian,Male,[70-80),1,1,7,6,13,...,No,No,No,No,No,No,No,No,No,NO

In [9]:
# Quantative and Qualitative

def qual_quan(data):
  qual=[]
  quan=[]
  for columnName in data.columns:
    if(data[columnName].dtypes=='O'):
      qual.append(columnName)
    else:
      quan.append(columnName)
  return quan,qual
qual_quan(data)

(['encounter_id',
  'patient_nbr',
  'admission_type_id',
  'discharge_disposition_id',
  'admission_source_id',
  'time_in_hospital',
  'num_lab_procedures',
  'num_procedures',
  'num_medications',
  'number_outpatient',
  'number_emergency',
  'number_inpatient',
  'number_diagnoses'],
 ['race',
  'gender',
  'age',
  'diag_1',
  'diag_2',
  'diag_3',
  'metformin',
  'repaglinide',
  'nateglinide',
  'chlorpropamide',
  'glimepiride',
  'acetohexamide',
  'glipizide',
  'glyburide',
  'tolbutamide',
  'pioglitazone',
  'rosiglitazone',
  'acarbose',
  'miglitol',
  'troglitazone',
  'tolazamide',
  'examide',
  'citoglipton',
  'insulin',
  'glyburide-metformin',
  'glipizide-metformin',
  'glimepiride-pioglitazone',
  'metformin-rosiglitazone',
  'metformin-pioglitazone',
  'change',
  'diabetesMed',
  'readmitted'])

In [10]:
quan,qual=qual_quan(data)

In [11]:
quan

['encounter_id',
 'patient_nbr',
 'admission_type_id',
 'discharge_disposition_id',
 'admission_source_id',
 'time_in_hospital',
 'num_lab_procedures',
 'num_procedures',
 'num_medications',
 'number_outpatient',
 'number_emergency',
 'number_inpatient',
 'number_diagnoses']

In [13]:
Descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","Q4:100%","%99","IQR","1.5rule","Lesser","Greater","Max","Min","Skewness","Kurtosis"],columns=quan)
for columnName in quan:
    Descriptive.loc["Mean", columnName] = data[columnName].mean()
    Descriptive.loc["Median", columnName] = data[columnName].median()
    Descriptive.loc["Mode", columnName] = data[columnName].mode()[0]
    Descriptive.loc["Q1:25%", columnName] = data.describe()[columnName]["25%"]
    Descriptive.loc["Q2:50%", columnName] = data.describe()[columnName]["50%"]
    Descriptive.loc["Q3:75%", columnName] = data.describe()[columnName]["75%"]
    Descriptive.loc["%99", columnName] = np.percentile(data[columnName],99)
    Descriptive.loc["Q4:100%", columnName] = data.describe()[columnName]["max"]
    Descriptive.loc["IQR", columnName] =Descriptive.loc["Q3:75%", columnName]- Descriptive.loc["Q1:25%", columnName]
    Descriptive.loc["1.5rule", columnName]=1.5*Descriptive.loc["IQR", columnName]
    Descriptive.loc["Lesser", columnName]=Descriptive.loc["Q1:25%", columnName]-Descriptive.loc["1.5rule", columnName]
    Descriptive.loc["Greater", columnName]=Descriptive.loc["Q3:75%", columnName]+Descriptive.loc["1.5rule", columnName]
    Descriptive.loc["Max", columnName] = data[columnName].max()
    Descriptive.loc["Min", columnName] = data[columnName].min()
    Descriptive.loc["Skewness", columnName] = data[columnName].skew()
    Descriptive.loc["Kurtosis", columnName] = data[columnName].kurtosis()


Descriptive

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
Mean,165201645.622978,54330400.694947,2.024006,3.715642,5.754437,4.395987,43.095641,1.33973,16.021844,0.369357,0.197836,0.635566,7.422607
Median,152388987.0,45505143.0,1.0,1.0,7.0,4.0,44.0,1.0,15.0,0.0,0.0,0.0,8.0
Mode,12522,88785891,1,1,7,3,1,0,13,0,0,0,9
Q1:25%,84961194.0,23413221.0,1.0,1.0,1.0,2.0,31.0,0.0,10.0,0.0,0.0,0.0,6.0
Q2:50%,152388987.0,45505143.0,1.0,1.0,7.0,4.0,44.0,1.0,15.0,0.0,0.0,0.0,8.0
Q3:75%,230270887.5,87545949.75,3.0,4.0,7.0,6.0,57.0,2.0,20.0,0.0,0.0,1.0,9.0
Q4:100%,443867222.0,189502619.0,8.0,28.0,25.0,14.0,132.0,6.0,81.0,42.0,76.0,21.0,16.0
%99,430219329.2,160818198.8,6.0,25.0,17.0,14.0,85.0,6.0,43.0,5.0,3.0,6.0,9.0
IQR,145309693.5,64132728.75,2.0,3.0,6.0,4.0,26.0,2.0,10.0,0.0,0.0,1.0,3.0
1.5rule,217964540.25,96199093.125,3.0,4.5,9.0,6.0,39.0,3.0,15.0,0.0,0.0,1.5,4.5
Lesser,-133003346.25,-72785872.125,-2.0,-3.5,-8.0,-4.0,-8.0,-3.0,-5.0,0.0,0.0,-1.5,1.5
Greater,448235427.75,183745042.875,6.0,8.5,16.0,12.0,96.0,5.0,35.0,0.0,0.0,2.5,13.5
Max,443867222,189502619,8,28,25,14,132,6,81,42,76,21,16
Min,12522,135,1,1,1,1,1,0,1,0,0,0,1
Skewness,0.699142,0.471281,1.591984,2.563067,1.029935,1.133999,-0.236544,1.316415,1.326672,8.832959,22.855582,3.614139,-0.876746
Kurtosis,-0.102071,-0.347372,1.942476,6.003347,1.744989,0.850251,-0.245074,0.85711,3.468155,147.907736,1191.686726,20.719397,-0.079056

In [16]:
Frequency=pd.DataFrame(columns=["Unique_Values","Frequency","Relative_Frequency","Cumulative_Frequency"])
Frequency["Unique_Values"]=data["readmitted"].value_counts().index
Frequency["Frequency"]=data["readmitted"].value_counts().values
Frequency["Relative_Frequency"]=(Frequency["Frequency"]/103)
Frequency["Cumulative_Frequency"]=Frequency["Relative_Frequency"].cumsum()
Frequency

  Unique_Values  Frequency  Relative_Frequency  Cumulative_Frequency
0            NO      54864          532.660194            532.660194
1           >30      35545          345.097087            877.757282
2           <30      11357          110.262136            988.019417

In [18]:
## Bivariate for Diabetic Readmission 
data.cov(numeric_only=True)

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
encounter_id,1.053503e+16,2.033677e+15,-2.358289e+07,-7.201319e+07,-4.688716e+07,-1.906392e+07,-5.262982e+07,-2.490548e+06,6.349488e+07,1.349577e+07,7.907967e+06,4.013309e+06,5.262284e+07
patient_nbr,2.033677e+15,1.497408e+15,-6.224166e+05,-2.795424e+07,-5.121875e+06,-2.782956e+06,1.214034e+07,-1.027757e+06,6.499150e+06,5.069566e+06,2.245038e+06,6.098915e+05,1.697340e+07
admission_type_id,-2.358289e+07,-6.224166e+05,2.089189e+00,6.371413e-01,6.265112e-01,-5.393206e-02,-4.086834e+00,3.202480e-01,9.343452e-01,4.855953e-02,-2.570937e-02,-6.965742e-02,-3.273466e-01
discharge_disposition_id,-7.201319e+07,-2.795424e+07,6.371413e-01,2.788015e+01,3.903983e-01,2.565205e+00,2.432424e+00,1.434002e-01,4.667127e+00,-5.831615e-02,-1.202281e-01,1.386135e-01,4.787441e-01
admission_source_id,-4.688716e+07,-5.121875e+06,6.265112e-01,3.903983e-01,1.651675e+01,-8.450143e-02,3.908732e+00,-9.386640e-01,-1.801288e+00,1.403158e-01,2.264819e-01,1.863783e-01,5.666972e-01
time_in_hospital,-1.906392e+07,-2.782956e+06,-5.393206e-02,2.565205e+00,-8.450143e-02,8.910868e+00,1.870261e+01,9.749771e-01,1.130922e+01,-3.372824e-02,-2.688944e-02,2.775411e-01,1.270916e+00
num_lab_procedures,-5.262982e+07,1.214034e+07,-4.086834e+00,2.432424e+00,3.908732e+00,1.870261e+01,3.870805e+02,1.948719e+00,4.288014e+01,-1.895441e-01,-4.172888e-02,9.747363e-01,5.811858e+00
num_procedures,-2.490548e+06,-1.027757e+06,3.202480e-01,1.434002e-01,-9.386640e-01,9.749771e-01,1.948719e+00,2.909777e+00,5.348300e+00,-5.365091e-02,-6.059835e-02,-1.426858e-01,2.431997e-01
num_medications,6.349488e+07,6.499150e+06,9.343452e-01,4.667127e+00,-1.801288e+00,1.130922e+01,4.288014e+01,5.348300e+00,6.605733e+01,4.655227e-01,9.967287e-02,6.588919e-01,4.110004e+00
number_outpatient,1.349577e+07,5.069566e+06,4.855953e-02,-5.831615e-02,1.403158e-01,-3.372824e-02,-1.895441e-01,-5.365091e-02,4.655227e-01,1.605961e+00,1.078439e-01,1.717815e-01,2.307086e-01
number_emergency,7.907967e+06,2.245038e+06,-2.570937e-02,-1.202281e-01,2.264819e-01,-2.688944e-02,-4.172888e-02,-6.059835e-02,9.967287e-02,1.078439e-01,8.657786e-01,3.132231e-01,9.992294e-02
number_inpatient,4.013309e+06,6.098915e+05,-6.965742e-02,1.386135e-01,1.863783e-01,2.775411e-01,9.747363e-01,-1.426858e-01,6.588919e-01,1.717815e-01,3.132231e-01,1.594824e+00,2.556893e-01
number_diagnoses,5.262284e+07,1.697340e+07,-3.273466e-01,4.787441e-01,5.666972e-01,1.270916e+00,5.811858e+00,2.431997e-01,4.110004e+00,2.307086e-01,9.992294e-02,2.556893e-01,3.738810e+00

In [19]:
data.corr(numeric_only=True)

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
encounter_id,1.000000,0.512028,-0.158961,-0.132876,-0.112402,-0.062221,-0.026062,-0.014225,0.076113,0.103756,0.082803,0.030962,0.265149
patient_nbr,0.512028,1.000000,-0.011128,-0.136814,-0.032568,-0.024092,0.015946,-0.015570,0.020665,0.103379,0.062352,0.012480,0.226847
admission_type_id,-0.158961,-0.011128,1.000000,0.083483,0.106654,-0.012500,-0.143713,0.129888,0.079535,0.026511,-0.019116,-0.038161,-0.117126
discharge_disposition_id,-0.132876,-0.136814,0.083483,1.000000,0.018193,0.162748,0.023415,0.015921,0.108753,-0.008715,-0.024471,0.020787,0.046891
admission_source_id,-0.112402,-0.032568,0.106654,0.018193,1.000000,-0.006965,0.048885,-0.135400,-0.054533,0.027244,0.059892,0.036314,0.072114
time_in_hospital,-0.062221,-0.024092,-0.012500,0.162748,-0.006965,1.000000,0.318450,0.191472,0.466135,-0.008916,-0.009681,0.073623,0.220186
num_lab_procedures,-0.026062,0.015946,-0.143713,0.023415,0.048885,0.318450,1.000000,0.058066,0.268161,-0.007602,-0.002279,0.039231,0.152773
num_procedures,-0.014225,-0.015570,0.129888,0.015921,-0.135400,0.191472,0.058066,1.000000,0.385767,-0.024819,-0.038179,-0.066236,0.073734
num_medications,0.076113,0.020665,0.079535,0.108753,-0.054533,0.466135,0.268161,0.385767,1.000000,0.045197,0.013180,0.064194,0.261526
number_outpatient,0.103756,0.103379,0.026511,-0.008715,0.027244,-0.008916,-0.007602,-0.024819,0.045197,1.000000,0.091459,0.107338,0.094152
number_emergency,0.082803,0.062352,-0.019116,-0.024471,0.059892,-0.009681,-0.002279,-0.038179,0.013180,0.091459,1.000000,0.266559,0.055539
number_inpatient,0.030962,0.012480,-0.038161,0.020787,0.036314,0.073623,0.039231,-0.066236,0.064194,0.107338,0.266559,1.000000,0.104710
number_diagnoses,0.265149,0.226847,-0.117126,0.046891,0.072114,0.220186,0.152773,0.073734,0.261526,0.094152,0.055539,0.104710,1.000000