In [1]:
##   Uniavriate 
import pandas as pd
import numpy as np
data = pd.read_csv(r"D:\smart decision\Data Preprocessing\Cleaned Datasets\cleaned_hospital_data_analysis.csv")
data

,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
0,45,Female,Heart Disease,Angioplasty,15000,5,No,Recovered,4
1,60,Male,Diabetes,Insulin Therapy,2000,3,Yes,Stable,3
2,32,Female,Fractured Arm,X-Ray and Splint,500,1,No,Recovered,5
3,75,Male,Stroke,CT Scan and Medication,10000,7,Yes,Stable,2
4,50,Female,Cancer,Surgery and Chemotherapy,25000,10,No,Recovered,4
...,...,...,...,...,...,...,...,...,...
979,68,Male,Hypertension,Medication and Counseling,1000,70,No,Stable,4
980,45,Female,Appendicitis,Appendectomy,8000,72,No,Recovered,3
981,40,Male,Fractured Leg,Cast and Physical Therapy,3000,72,No,Recovered,4
982,78,Female,Heart Attack,Cardiac Catheterization,18000,74,Yes,Stable,2
983,25,Male,Allergic Reaction,Epinephrine Injection,100,68,No,Recovered,5

In [2]:
# Quantative and Qualitative

def qual_quan(data):
  qual=[]
  quan=[]
  for columnName in data.columns:
    if(data[columnName].dtypes=='O'):
      qual.append(columnName)
    else:
      quan.append(columnName)
  return quan,qual
qual_quan(data)

(['Age', 'Cost', 'Length_of_Stay', 'Satisfaction'],
 ['Gender', 'Condition', 'Procedure', 'Readmission', 'Outcome'])

In [3]:
quan,qual=qual_quan(data)

In [4]:
quan

['Age', 'Cost', 'Length_of_Stay', 'Satisfaction']

In [5]:
Descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","Q4:100%","%99","IQR","1.5rule","Lesser","Greater","Max","Min","Skewness","Kurtosis"],columns=quan)
for columnName in quan:
    Descriptive.loc["Mean", columnName] = data[columnName].mean()
    Descriptive.loc["Median", columnName] = data[columnName].median()
    Descriptive.loc["Mode", columnName] = data[columnName].mode()[0]
    Descriptive.loc["Q1:25%", columnName] = data.describe()[columnName]["25%"]
    Descriptive.loc["Q2:50%", columnName] = data.describe()[columnName]["50%"]
    Descriptive.loc["Q3:75%", columnName] = data.describe()[columnName]["75%"]
    Descriptive.loc["%99", columnName] = np.percentile(data[columnName],99)
    Descriptive.loc["Q4:100%", columnName] = data.describe()[columnName]["max"]
    Descriptive.loc["IQR", columnName] =Descriptive.loc["Q3:75%", columnName]- Descriptive.loc["Q1:25%", columnName]
    Descriptive.loc["1.5rule", columnName]=1.5*Descriptive.loc["IQR", columnName]
    Descriptive.loc["Lesser", columnName]=Descriptive.loc["Q1:25%", columnName]-Descriptive.loc["1.5rule", columnName]
    Descriptive.loc["Greater", columnName]=Descriptive.loc["Q3:75%", columnName]+Descriptive.loc["1.5rule", columnName]
    Descriptive.loc["Max", columnName] = data[columnName].max()
    Descriptive.loc["Min", columnName] = data[columnName].min()
    Descriptive.loc["Skewness", columnName] = data[columnName].skew()
    Descriptive.loc["Kurtosis", columnName] = data[columnName].kurtosis()


Descriptive

                Age         Cost Length_of_Stay Satisfaction
Mean      53.754065  8367.479675      37.663618     3.598577
Median         55.0       6000.0           38.0          4.0
Mode             55         3000             10            4
Q1:25%         45.0       1000.0           21.0          3.0
Q2:50%         55.0       6000.0           38.0          4.0
Q3:75%         65.0      15000.0          54.25          4.0
Q4:100%        78.0      25000.0           76.0          5.0
%99            78.0      25000.0          72.17          5.0
IQR            20.0      14000.0          33.25          1.0
1.5rule        30.0      21000.0         49.875          1.5
Lesser         15.0     -20000.0        -28.875          1.5
Greater        95.0      36000.0        104.125          5.5
Max              78        25000             76            5
Min              25          100              1            2
Skewness  -0.244515       0.7213       0.001134    -0.305531
Kurtosis  -0.868534    -0.721782      -1.159031    -0.613206

In [7]:
Frequency=pd.DataFrame(columns=["Unique_Values","Frequency","Relative_Frequency","Cumulative_Frequency"])
Frequency["Unique_Values"]=data["Satisfaction"].value_counts().index
Frequency["Frequency"]=data["Satisfaction"].value_counts().values
Frequency["Relative_Frequency"]=(Frequency["Frequency"]/103)
Frequency["Cumulative_Frequency"]=Frequency["Relative_Frequency"].cumsum()
Frequency

   Unique_Values  Frequency  Relative_Frequency  Cumulative_Frequency
0              4        458            4.446602              4.446602
1              3        261            2.533981              6.980583
2              2        133            1.291262              8.271845
3              5        132            1.281553              9.553398

In [8]:
## Bivariate 
data.cov(numeric_only=True)

                         Age          Cost  Length_of_Stay  Satisfaction
Age               223.237522  3.523442e+04       21.982295     -9.900452
Cost            35234.415139  6.024850e+07    17371.043512  -3218.967984
Length_of_Stay     21.982295  1.737104e+04      383.995582     -1.399665
Satisfaction       -9.900452 -3.218968e+03       -1.399665      0.779693

In [9]:
data.corr(numeric_only=True)

                     Age      Cost  Length_of_Stay  Satisfaction
Age             1.000000  0.303816        0.075080     -0.750429
Cost            0.303816  1.000000        0.114206     -0.469658
Length_of_Stay  0.075080  0.114206        1.000000     -0.080891
Satisfaction   -0.750429 -0.469658       -0.080891      1.000000

In [11]:
## T test
from scipy.stats import ttest_ind

male = data[data['Gender']=='Male']['Cost']
female = data[data['Gender']=='Female']['Cost']

ttest_ind(male, female)

TtestResult(statistic=np.float64(-9.410128016628969), pvalue=np.float64(3.4028401786586644e-20), df=np.float64(982.0))

In [12]:
### ANOVA

import scipy.stats as stats
stats.f_oneway(data['Age'],data['Cost'],data['Satisfaction'])

F_onewayResult(statistic=np.float64(1135.707424023147), pvalue=np.float64(0.0))