In [2]:
##   Uniavriate 
import pandas as pd
import numpy as np
data = pd.read_csv(r"D:\smart decision\Data Preprocessing\Cleaned Datasets\cleaned_LengthOfStay.csv")
data

,vdate,rcount,gender,dialysisrenalendstage,asthma,irondef,pneum,substancedependence,psychologicaldisordermajor,depress,...,glucose,bloodureanitro,creatinine,bmi,pulse,respiration,secondarydiagnosisnonicd9,discharged,facid,lengthofstay
0,8/29/2012,0,F,0,0,0,0,0,0,0,...,192.476918,12.0,1.390722,30.432418,96,6.5,4,9/1/2012,B,3
1,5/26/2012,5+,F,0,0,0,0,0,0,0,...,94.078507,8.0,0.943164,28.460516,61,6.5,1,6/2/2012,A,7
2,9/22/2012,1,F,0,0,0,0,0,0,0,...,130.530524,12.0,1.065750,28.843812,64,6.5,2,9/25/2012,B,3
3,8/9/2012,0,F,0,0,0,0,0,0,0,...,163.377028,12.0,0.906862,27.959007,76,6.5,1,8/10/2012,A,1
4,12/20/2012,0,F,0,0,0,1,0,1,0,...,94.886654,11.5,1.242854,30.258927,67,5.6,2,12/24/2012,E,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1/28/2012,3,M,0,0,0,0,0,0,0,...,171.422555,12.0,0.650323,30.063069,80,6.5,1,2/3/2012,B,6
99996,8/6/2012,0,M,0,0,0,0,0,0,0,...,122.342450,12.0,1.521424,28.969548,61,6.5,1,8/7/2012,B,1
99997,7/23/2012,1,M,0,0,1,0,0,0,0,...,108.288106,12.0,1.025677,26.354919,61,6.9,1,7/27/2012,C,4
99998,12/19/2012,0,M,0,0,0,0,0,0,1,...,111.750731,16.0,1.035400,29.193462,59,5.6,1,12/23/2012,B,4
99999,3/6/2012,0,F,0,0,0,0,0,0,0,...,149.572205,12.0,0.813004,25.175760,74,6.5,4,3/8/2012,B,2

In [3]:
# Quantative and Qualitative

def qual_quan(data):
  qual=[]
  quan=[]
  for columnName in data.columns:
    if(data[columnName].dtypes=='O'):
      qual.append(columnName)
    else:
      quan.append(columnName)
  return quan,qual
qual_quan(data)

(['dialysisrenalendstage',
  'asthma',
  'irondef',
  'pneum',
  'substancedependence',
  'psychologicaldisordermajor',
  'depress',
  'psychother',
  'fibrosisandother',
  'malnutrition',
  'hemo',
  'hematocrit',
  'neutrophils',
  'sodium',
  'glucose',
  'bloodureanitro',
  'creatinine',
  'bmi',
  'pulse',
  'respiration',
  'secondarydiagnosisnonicd9',
  'lengthofstay'],
 ['vdate', 'rcount', 'gender', 'discharged', 'facid'])

In [4]:
quan,qual=qual_quan(data)

In [5]:
quan

['dialysisrenalendstage',
 'asthma',
 'irondef',
 'pneum',
 'substancedependence',
 'psychologicaldisordermajor',
 'depress',
 'psychother',
 'fibrosisandother',
 'malnutrition',
 'hemo',
 'hematocrit',
 'neutrophils',
 'sodium',
 'glucose',
 'bloodureanitro',
 'creatinine',
 'bmi',
 'pulse',
 'respiration',
 'secondarydiagnosisnonicd9',
 'lengthofstay']

In [8]:
Descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","Q4:100%","%99","IQR","1.5rule","Lesser","Greater","Max","Min","Skewness","Kurtosis"],columns=quan)
for columnName in quan:
    Descriptive.loc["Mean", columnName] = data[columnName].mean()
    Descriptive.loc["Median", columnName] = data[columnName].median()
    Descriptive.loc["Mode", columnName] = data[columnName].mode()[0]
    Descriptive.loc["Q1:25%", columnName] = data.describe()[columnName]["25%"]
    Descriptive.loc["Q2:50%", columnName] = data.describe()[columnName]["50%"]
    Descriptive.loc["Q3:75%", columnName] = data.describe()[columnName]["75%"]
    Descriptive.loc["%99", columnName] = np.percentile(data[columnName],99)
    Descriptive.loc["Q4:100%", columnName] = data.describe()[columnName]["max"]
    Descriptive.loc["IQR", columnName] =Descriptive.loc["Q3:75%", columnName]- Descriptive.loc["Q1:25%", columnName]
    Descriptive.loc["1.5rule", columnName]=1.5*Descriptive.loc["IQR", columnName]
    Descriptive.loc["Lesser", columnName]=Descriptive.loc["Q1:25%", columnName]-Descriptive.loc["1.5rule", columnName]
    Descriptive.loc["Greater", columnName]=Descriptive.loc["Q3:75%", columnName]+Descriptive.loc["1.5rule", columnName]
    Descriptive.loc["Max", columnName] = data[columnName].max()
    Descriptive.loc["Min", columnName] = data[columnName].min()
    Descriptive.loc["Skewness", columnName] = data[columnName].skew()
    Descriptive.loc["Kurtosis", columnName] = data[columnName].kurtosis()


Descriptive

,dialysisrenalendstage,asthma,irondef,pneum,substancedependence,psychologicaldisordermajor,depress,psychother,fibrosisandother,malnutrition,...,neutrophils,sodium,glucose,bloodureanitro,creatinine,bmi,pulse,respiration,secondarydiagnosisnonicd9,lengthofstay
Mean,0.03642,0.03527,0.09494,0.03945,0.06306,0.23904,0.05166,0.04939,0.00479,0.04948,...,10.177455,137.891397,141.963384,14.097185,1.09935,29.805759,73.44472,6.493768,2.12331,4.00103
Median,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9.4,137.887151,142.088545,12.0,1.098764,29.807516,73.0,6.5,1.0,4.0
Mode,0,0,0,0,0,0,0,0,0,0,...,9.4,133.816514,129.720211,12.0,0.896881,27.843315,71,6.5,1,1
Q1:25%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.7,135.871062,121.682383,11.0,0.96472,28.454235,66.0,6.5,1.0,2.0
Q2:50%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9.4,137.887151,142.088545,12.0,1.098764,29.807516,73.0,6.5,1.0,4.0
Q3:75%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,11.5,139.912885,162.180996,14.0,1.234867,31.156885,81.0,6.5,3.0,6.0
Q4:100%,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,245.9,151.387283,271.444277,682.5,2.035202,38.935293,130.0,10.0,10.0,17.0
%99,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,...,25.0,144.857665,211.156559,53.0,1.564592,34.45472,101.0,8.2,10.0,10.0
IQR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.8,4.041822,40.498612,3.0,0.270147,2.70265,15.0,0.0,2.0,4.0
1.5rule,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.7,6.062734,60.747918,4.5,0.405221,4.053974,22.5,0.0,3.0,6.0
Lesser,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,129.808329,60.934465,6.5,0.559499,24.400261,43.5,6.5,-2.0,-4.0
Greater,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,17.2,145.975618,222.928914,18.5,1.640089,35.210859,103.5,6.5,6.0,12.0
Max,1,1,1,1,1,1,1,1,1,1,...,245.9,151.387283,271.444277,682.5,2.035202,38.935293,130,10.0,10,17
Min,0,0,0,0,0,0,0,0,0,0,...,0.1,124.912632,-1.005927,1.0,0.21977,21.992683,21,0.2,0,1
Skewness,4.949341,5.038852,2.763711,4.731837,3.59522,1.223754,4.05121,4.159265,14.345008,4.154848,...,13.281389,0.001065,-0.012905,17.286481,0.001208,0.010573,0.001344,-0.551864,1.672659,0.628235
Kurtosis,22.496422,23.390497,5.638209,20.390692,10.925824,-0.502435,14.412591,15.299795,203.783329,15.263065,...,428.439819,0.016395,0.011968,528.553257,-0.007996,0.000493,0.030821,8.302673,2.630753,-0.025059

In [10]:
Frequency=pd.DataFrame(columns=["Unique_Values","Frequency","Relative_Frequency","Cumulative_Frequency"])
Frequency["Unique_Values"]=data["lengthofstay"].value_counts().index
Frequency["Frequency"]=data["lengthofstay"].value_counts().values
Frequency["Relative_Frequency"]=(Frequency["Frequency"]/103)
Frequency["Cumulative_Frequency"]=Frequency["Relative_Frequency"].cumsum()
Frequency

    Unique_Values  Frequency  Relative_Frequency  Cumulative_Frequency
0               1      17979          174.553398            174.553398
1               3      16068          156.000000            330.553398
2               4      14822          143.902913            474.456311
3               2      12825          124.514563            598.970874
4               5      12116          117.631068            716.601942
5               6      10362          100.601942            817.203883
6               7       7263           70.514563            887.718447
7               8       4652           45.165049            932.883495
8               9       2184           21.203883            954.087379
9              10       1000            9.708738            963.796117
10             11        460            4.466019            968.262136
11             12        137            1.330097            969.592233
12             13         75            0.728155            970.320388
13             14         31            0.300971            970.621359
14             15         16            0.155340            970.776699
15             16          6            0.058252            970.834951
16             17          4            0.038835            970.873786

In [11]:
## Bivariate
data.corr(numeric_only=True)

,dialysisrenalendstage,asthma,irondef,pneum,substancedependence,psychologicaldisordermajor,depress,psychother,fibrosisandother,malnutrition,...,neutrophils,sodium,glucose,bloodureanitro,creatinine,bmi,pulse,respiration,secondarydiagnosisnonicd9,lengthofstay
dialysisrenalendstage,1.000000,-0.005340,0.157381,0.120472,0.049925,0.085162,0.013229,0.311179,0.018211,0.209172,...,-0.053125,-0.000198,-0.003199,0.272239,-0.000372,0.003331,0.003802,-0.043435,0.003251,0.169695
asthma,-0.005340,1.000000,0.020001,0.058444,-0.005668,0.026300,0.026402,-0.008556,0.015787,0.008620,...,0.016505,-0.004474,0.000641,-0.005675,-0.001479,-0.000597,0.006473,0.001910,-0.001108,0.082005
irondef,0.157381,0.020001,1.000000,0.151320,0.082848,0.127544,0.019041,0.176662,0.021999,0.300174,...,-0.078817,-0.001443,-0.000598,0.149846,-0.010980,-0.005841,0.002803,-0.047849,0.006194,0.193838
pneum,0.120472,0.058444,0.151320,1.000000,0.076131,0.089732,0.016293,0.090839,0.025374,0.133551,...,-0.005961,-0.003280,-0.000981,0.064899,-0.001437,0.000650,0.005045,-0.055898,0.000590,0.135461
substancedependence,0.049925,-0.005668,0.082848,0.076131,1.000000,0.081762,0.004690,0.087252,0.007624,0.048180,...,-0.062084,0.001232,0.001923,0.073065,0.002481,-0.001434,0.002433,-0.058826,-0.000814,0.147886
psychologicaldisordermajor,0.085162,0.026300,0.127544,0.089732,0.081762,1.000000,0.295137,0.096239,0.015112,0.119817,...,-0.119881,-0.001268,-0.003387,0.073234,-0.000066,-0.000749,0.000377,0.065988,0.005916,0.286724
depress,0.013229,0.026402,0.019041,0.016293,0.004690,0.295137,1.000000,-0.001908,0.011945,0.019038,...,-0.053935,-0.005884,0.003777,0.007889,-0.002212,0.001648,0.007289,0.040031,0.001255,0.121408
psychother,0.311179,-0.008556,0.176662,0.090839,0.087252,0.096239,-0.001908,1.000000,0.002234,0.310403,...,-0.083957,0.000311,-0.000414,0.347354,-0.005638,0.002643,0.001140,-0.028148,0.006368,0.191695
fibrosisandother,0.018211,0.015787,0.021999,0.025374,0.007624,0.015112,0.011945,0.002234,1.000000,0.031589,...,0.170259,0.000709,0.007347,0.021765,-0.002226,-0.004844,-0.000038,-0.038565,0.000843,0.062131
malnutrition,0.209172,0.008620,0.300174,0.133551,0.048180,0.119817,0.019038,0.310403,0.031589,1.000000,...,-0.070872,0.002080,-0.000157,0.267992,-0.004023,-0.002759,0.005217,-0.018937,0.009576,0.174397
hemo,0.177411,0.015954,0.125682,0.088315,0.084697,0.066088,0.027931,0.197482,0.059089,0.134131,...,-0.040737,0.003227,-0.003971,0.109893,-0.001130,-0.001775,0.005638,-0.103263,-0.001069,0.217696
hematocrit,-0.120281,-0.032994,-0.054934,-0.076968,-0.106387,0.046264,0.026997,-0.147034,-0.057582,-0.085470,...,0.122385,0.002700,-0.000982,-0.073813,-0.001900,-0.002666,-0.001839,0.206028,0.001957,-0.064016
neutrophils,-0.053125,0.016505,-0.078817,-0.005961,-0.062084,-0.119881,-0.053935,-0.083957,0.170259,-0.070872,...,1.000000,-0.000810,0.000528,-0.045316,-0.001679,-0.005275,-0.000144,-0.044416,0.002206,-0.010658
sodium,-0.000198,-0.004474,-0.001443,-0.003280,0.001232,-0.001268,-0.005884,0.000311,0.000709,0.002080,...,-0.000810,1.000000,0.002834,-0.003736,0.003037,0.001101,-0.003567,-0.001444,0.001040,-0.003546
glucose,-0.003199,0.000641,-0.000598,-0.000981,0.001923,-0.003387,0.003777,-0.000414,0.007347,-0.000157,...,0.000528,0.002834,1.000000,-0.002247,-0.003412,-0.000024,0.008141,-0.000431,0.002813,-0.003447
bloodureanitro,0.272239,-0.005675,0.149846,0.064899,0.073065,0.073234,0.007889,0.347354,0.021765,0.267992,...,-0.045316,-0.003736,-0.002247,1.000000,0.000154,0.002589,0.007087,0.006773,0.001919,0.148290
creatinine,-0.000372,-0.001479,-0.010980,-0.001437,0.002481,-0.000066,-0.002212,-0.005638,-0.002226,-0.004023,...,-0.001679,0.003037,-0.003412,0.000154,1.000000,-0.005074,-0.000620,-0.001798,-0.003675,-0.004026
bmi,0.003331,-0.000597,-0.005841,0.000650,-0.001434,-0.000749,0.001648,0.002643,-0.004844,-0.002759,...,-0.005275,0.001101,-0.000024,0.002589,-0.005074,1.000000,-0.000934,-0.001450,-0.001691,0.000132
pulse,0.003802,0.006473,0.002803,0.005045,0.002433,0.000377,0.007289,0.001140,-0.000038,0.005217,...,-0.000144,-0.003567,0.008141,0.007087,-0.000620,-0.000934,1.000000,-0.003162,-0.003022,0.006683
respiration,-0.043435,0.001910,-0.047849,-0.055898,-0.058826,0.065988,0.040031,-0.028148,-0.038565,-0.018937,...,-0.044416,-0.001444,-0.000431,0.006773,-0.001798,-0.001450,-0.003162,1.000000,-0.000647,-0.022291
secondarydiagnosisnonicd9,0.003251,-0.001108,0.006194,0.000590,-0.000814,0.005916,0.001255,0.006368,0.000843,0.009576,...,0.002206,0.001040,0.002813,0.001919,-0.003675,-0.001691,-0.003022,-0.000647,1.000000,0.006540
lengthofstay,0.169695,0.082005,0.193838,0.135461,0.147886,0.286724,0.121408,0.191695,0.062131,0.174397,...,-0.010658,-0.003546,-0.003447,0.148290,-0.004026,0.000132,0.006683,-0.022291,0.006540,1.000000

In [12]:
data.cov(numeric_only=True)

,dialysisrenalendstage,asthma,irondef,pneum,substancedependence,psychologicaldisordermajor,depress,psychother,fibrosisandother,malnutrition,...,neutrophils,sodium,glucose,bloodureanitro,creatinine,bmi,pulse,respiration,secondarydiagnosisnonicd9,lengthofstay
dialysisrenalendstage,0.035094,-0.000185,0.008642,0.004393,0.002273,0.006804,0.000549,0.012631,0.000236,0.008498,...,-0.053275,-0.000111,-0.017974,0.660570,-0.000014,0.001250,0.008293,-0.004626,0.001249,0.075033
asthma,-0.000185,0.034026,0.001081,0.002099,-0.000254,0.002069,0.001078,-0.000342,0.000201,0.000345,...,0.016298,-0.002476,0.003544,-0.013558,-0.000055,-0.000221,0.013905,0.000200,-0.000419,0.035704
irondef,0.008642,0.001081,0.085927,0.008635,0.005903,0.015946,0.001235,0.011221,0.000445,0.019083,...,-0.123678,-0.001269,-0.005259,0.568936,-0.000645,-0.003431,0.009568,-0.007973,0.003723,0.134114
pneum,0.004393,0.002099,0.008635,0.037894,0.003602,0.007450,0.000702,0.003832,0.000341,0.005638,...,-0.006211,-0.001916,-0.005726,0.163634,-0.000056,0.000253,0.011436,-0.006186,0.000235,0.062240
substancedependence,0.002273,-0.000254,0.005903,0.003602,0.059084,0.008476,0.000252,0.004596,0.000128,0.002540,...,-0.080783,0.000898,0.014017,0.230037,0.000121,-0.000698,0.006886,-0.008129,-0.000406,0.084846
psychologicaldisordermajor,0.006804,0.002069,0.015946,0.007450,0.008476,0.181902,0.027861,0.008894,0.000445,0.011082,...,-0.273702,-0.001623,-0.043327,0.404558,-0.000006,-0.000640,0.001874,0.015999,0.005174,0.288637
depress,0.000549,0.001078,0.001235,0.000702,0.000252,0.027861,0.048992,-0.000091,0.000183,0.000914,...,-0.063905,-0.003907,0.025072,0.022617,-0.000098,0.000731,0.018786,0.005037,0.000570,0.063427
psychother,0.012631,-0.000342,0.011221,0.003832,0.004596,0.008894,-0.000091,0.046951,0.000033,0.014586,...,-0.097384,0.000202,-0.002691,0.974872,-0.000245,0.001148,0.002875,-0.003467,0.002830,0.098040
fibrosisandother,0.000236,0.000201,0.000445,0.000341,0.000128,0.000445,0.000183,0.000033,0.004767,0.000473,...,0.062928,0.000147,0.015215,0.019465,-0.000031,-0.000670,-0.000030,-0.001514,0.000119,0.010125
malnutrition,0.008498,0.000345,0.019083,0.005638,0.002540,0.011082,0.000914,0.014586,0.000473,0.047032,...,-0.082277,0.001353,-0.001020,0.752785,-0.000175,-0.001199,0.013175,-0.002335,0.004259,0.089270
hemo,0.009016,0.000798,0.009995,0.004664,0.005585,0.007647,0.001677,0.011609,0.001107,0.007892,...,-0.059162,0.002626,-0.032311,0.386157,-0.000061,-0.000965,0.017813,-0.015926,-0.000595,0.139399
hematocrit,-0.045782,-0.012366,-0.032718,-0.030442,-0.052542,0.040090,0.012141,-0.064732,-0.008078,-0.037661,...,1.331118,0.016458,-0.059834,-1.942513,-0.000773,-0.010856,-0.043503,0.237966,0.008155,-0.306997
neutrophils,-0.053275,0.016298,-0.123678,-0.006211,-0.080783,-0.273702,-0.063905,-0.097384,0.062928,-0.082277,...,28.656011,-0.013004,0.084822,-3.142022,-0.001800,-0.056580,-0.008966,-0.135162,0.024212,-0.134662
sodium,-0.000111,-0.002476,-0.001269,-0.001916,0.000898,-0.001623,-0.003907,0.000202,0.000147,0.001353,...,-0.013004,8.998012,0.254968,-0.145150,0.001824,0.006617,-0.124600,-0.002463,0.006396,-0.025103
glucose,-0.017974,0.003544,-0.005259,-0.005726,0.014017,-0.043327,0.025072,-0.002691,0.015215,-0.001020,...,0.084822,0.254968,899.579812,-0.872819,-0.020492,-0.001450,2.843260,-0.007345,0.173007,-0.244052
bloodureanitro,0.660570,-0.013558,0.568936,0.163634,0.230037,0.404558,0.022617,0.974872,0.019465,0.752785,...,-3.142022,-0.145150,-0.872819,167.766074,0.000399,0.067197,1.068881,0.049868,0.050973,4.533492
creatinine,-0.000014,-0.000055,-0.000645,-0.000056,0.000121,-0.000006,-0.000098,-0.000245,-0.000031,-0.000175,...,-0.001800,0.001824,-0.020492,0.000399,0.040105,-0.002036,-0.001446,-0.000205,-0.001509,-0.001903
bmi,0.001250,-0.000221,-0.003431,0.000253,-0.000698,-0.000640,0.000731,0.001148,-0.000670,-0.001199,...,-0.056580,0.006617,-0.001450,0.067197,-0.002036,4.015090,-0.021783,-0.001651,-0.006950,0.000625
pulse,0.008293,0.013905,0.009568,0.011436,0.006886,0.001874,0.018786,0.002875,-0.000030,0.013175,...,-0.008966,-0.124600,2.843260,1.068881,-0.001446,-0.021783,135.595660,-0.020934,-0.072169,0.183694
respiration,-0.004626,0.000200,-0.007973,-0.006186,-0.008129,0.015999,0.005037,-0.003467,-0.001514,-0.002335,...,-0.135162,-0.002463,-0.007345,0.049868,-0.000205,-0.001651,-0.020934,0.323161,-0.000754,-0.029909
secondarydiagnosisnonicd9,0.001249,-0.000419,0.003723,0.000235,-0.000406,0.005174,0.000570,0.002830,0.000119,0.004259,...,0.024212,0.006396,0.173007,0.050973,-0.001509,-0.006950,-0.072169,-0.000754,4.205127,0.031653
lengthofstay,0.075033,0.035704,0.134114,0.062240,0.084846,0.288637,0.063427,0.098040,0.010125,0.089270,...,-0.134662,-0.025103,-0.244052,4.533492,-0.001903,0.000625,0.183694,-0.029909,0.031653,5.571065