In [1]:
##   Uniavriate 
import pandas as pd
import numpy as np
data = pd.read_csv(r"D:\smart decision\Data Preprocessing\Cleaned Datasets\cleaned_clinical_pneumonia_dataset.csv")
data

,timestamp,fever,tachycardia,crackles,oxygen_saturation,wbc_count,chest_xray_result,true_label,uncertainty_score
0,2022-06-11,1,1,1,93.500000,7.500000,consolidation,pneumonia,0.77
1,2022-06-12,1,1,1,93.500000,7.500000,consolidation,pneumonia,0.85
2,2022-06-13,1,1,1,93.500000,7.500000,consolidation,pneumonia,0.96
3,2022-06-14,0,1,1,92.458450,7.648591,consolidation,pneumonia,0.82
4,2022-06-15,1,1,1,92.280835,7.871925,effusion,pneumonia,0.83
...,...,...,...,...,...,...,...,...,...
1495,2022-07-08,1,1,1,96.900000,8.200000,normal,atelectasis,0.78
1496,2022-07-09,1,1,1,96.900000,8.200000,consolidation,atelectasis,0.50
1497,2022-07-10,1,1,1,96.900000,8.200000,consolidation,atelectasis,0.43
1498,2022-07-11,1,1,1,95.952182,8.687035,opacity,atelectasis,0.61
1499,2022-07-12,1,1,1,96.169921,8.302767,consolidation,atelectasis,0.56

In [2]:
# Quantative and Qualitative

def qual_quan(data):
  qual=[]
  quan=[]
  for columnName in data.columns:
    if(data[columnName].dtypes=='O'):
      qual.append(columnName)
    else:
      quan.append(columnName)
  return quan,qual
qual_quan(data)

(['fever',
  'tachycardia',
  'crackles',
  'oxygen_saturation',
  'wbc_count',
  'uncertainty_score'],
 ['timestamp', 'chest_xray_result', 'true_label'])

In [3]:
quan,qual=qual_quan(data)

In [4]:
quan

['fever',
 'tachycardia',
 'crackles',
 'oxygen_saturation',
 'wbc_count',
 'uncertainty_score']

In [5]:
Descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","Q4:100%","%99","IQR","1.5rule","Lesser","Greater","Max","Min","Skewness","Kurtosis"],columns=quan)
for columnName in quan:
    Descriptive.loc["Mean", columnName] = data[columnName].mean()
    Descriptive.loc["Median", columnName] = data[columnName].median()
    Descriptive.loc["Mode", columnName] = data[columnName].mode()[0]
    Descriptive.loc["Q1:25%", columnName] = data.describe()[columnName]["25%"]
    Descriptive.loc["Q2:50%", columnName] = data.describe()[columnName]["50%"]
    Descriptive.loc["Q3:75%", columnName] = data.describe()[columnName]["75%"]
    Descriptive.loc["%99", columnName] = np.percentile(data[columnName],99)
    Descriptive.loc["Q4:100%", columnName] = data.describe()[columnName]["max"]
    Descriptive.loc["IQR", columnName] =Descriptive.loc["Q3:75%", columnName]- Descriptive.loc["Q1:25%", columnName]
    Descriptive.loc["1.5rule", columnName]=1.5*Descriptive.loc["IQR", columnName]
    Descriptive.loc["Lesser", columnName]=Descriptive.loc["Q1:25%", columnName]-Descriptive.loc["1.5rule", columnName]
    Descriptive.loc["Greater", columnName]=Descriptive.loc["Q3:75%", columnName]+Descriptive.loc["1.5rule", columnName]
    Descriptive.loc["Max", columnName] = data[columnName].max()
    Descriptive.loc["Min", columnName] = data[columnName].min()
    Descriptive.loc["Skewness", columnName] = data[columnName].skew()
    Descriptive.loc["Kurtosis", columnName] = data[columnName].kurtosis()


Descriptive

,fever,tachycardia,crackles,oxygen_saturation,wbc_count,uncertainty_score
Mean,0.757333,0.61,0.540667,94.591672,8.459798,0.660627
Median,1.0,1.0,1.0,94.643829,8.5,0.7
Mode,1,1,1,94.3,7.0,0.8
Q1:25%,1.0,0.0,0.0,93.094371,7.4,0.49
Q2:50%,1.0,1.0,1.0,94.643829,8.5,0.7
Q3:75%,1.0,1.0,1.0,96.2,9.5,0.81
Q4:100%,1.0,1.0,1.0,98.0,10.860768,0.99
%99,1.0,1.0,1.0,97.9,10.695592,0.98
IQR,0.0,1.0,1.0,3.105629,2.1,0.32
1.5rule,0.0,1.5,1.5,4.658444,3.15,0.48
Lesser,1.0,-1.5,-1.5,88.435926,4.25,0.01
Greater,1.0,2.5,2.5,100.858444,12.65,1.29
Max,1,1,1,98.0,10.860768,0.99
Min,0,0,0,90.519648,6.0,0.3
Skewness,-1.201744,-0.451502,-0.163371,-0.071901,-0.104945,-0.22861
Kurtosis,-0.556554,-1.798545,-1.975946,-1.031948,-1.080088,-1.104529

In [7]:
Frequency=pd.DataFrame(columns=["Unique_Values","Frequency","Relative_Frequency","Cumulative_Frequency"])
Frequency["Unique_Values"]=data["true_label"].value_counts().index
Frequency["Frequency"]=data["true_label"].value_counts().values
Frequency["Relative_Frequency"]=(Frequency["Frequency"]/103)
Frequency["Cumulative_Frequency"]=Frequency["Relative_Frequency"].cumsum()
Frequency

     Unique_Values  Frequency  Relative_Frequency  Cumulative_Frequency
0        pneumonia        500            4.854369              4.854369
1  pulmonary edema        500            4.854369              9.708738
2      atelectasis        500            4.854369             14.563107

In [8]:
## Bivariate
data.corr(numeric_only=True)

,fever,tachycardia,crackles,oxygen_saturation,wbc_count,uncertainty_score
fever,1.000000,-0.028567,0.018108,-0.000732,0.039417,0.015826
tachycardia,-0.028567,1.000000,0.006281,0.040610,-0.024078,-0.046908
crackles,0.018108,0.006281,1.000000,-0.046151,0.098910,0.209562
oxygen_saturation,-0.000732,0.040610,-0.046151,1.000000,-0.032214,0.028715
wbc_count,0.039417,-0.024078,0.098910,-0.032214,1.000000,0.009814
uncertainty_score,0.015826,-0.046908,0.209562,0.028715,0.009814,1.000000

In [9]:
data.cov(numeric_only=True)

,fever,tachycardia,crackles,oxygen_saturation,wbc_count,uncertainty_score
fever,0.183902,-0.005977,0.003871,-0.000584,0.021485,0.001306
tachycardia,-0.005977,0.238059,0.001528,0.036864,-0.014932,-0.004405
crackles,0.003871,0.001528,0.248512,-0.042803,0.062671,0.020108
oxygen_saturation,-0.000584,0.036864,-0.042803,3.461335,-0.076178,0.010283
wbc_count,0.021485,-0.014932,0.062671,-0.076178,1.615519,0.002401
uncertainty_score,0.001306,-0.004405,0.020108,0.010283,0.002401,0.037048